"""empty message

Revision ID: 00a4502a210a
Revises: fcdb39ddf6cb
Create Date: 2022-06-23 16:04:03.618366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00a4502a210a'
down_revision = 'fcdb39ddf6cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('caterer_get_food_category', 'food_category_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('caterer_get_food_category', 'caterer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('caterer_get_food_category', 'id')
    op.alter_column('decorator_get_types', 'decorator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('decorator_get_types', 'decoration_type_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('decorator_get_types', 'id')
    op.alter_column('venue_get_caterer', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('venue_get_caterer', 'caterer_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('venue_get_caterer', 'id')
    op.alter_column('venue_get_decorator', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('venue_get_decorator', 'decorator_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue_get_decorator', 'decorator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('venue_get_decorator', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('venue_get_caterer', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('venue_get_caterer', 'caterer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('venue_get_caterer', 'venue_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('decorator_get_types', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('decorator_get_types', 'decoration_type_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('decorator_get_types', 'decorator_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('caterer_get_food_category', sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False))
    op.alter_column('caterer_get_food_category', 'caterer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('caterer_get_food_category', 'food_category_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
