"""empty message

Revision ID: 0ad0da67640a
Revises: 53fcb5737f25
Create Date: 2022-07-08 09:48:09.323250

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ad0da67640a'
down_revision = '53fcb5737f25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'charges')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('charges', sa.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
