"""empty message

Revision ID: 1dfedcf64719
Revises: 3f2a3265ed46
Create Date: 2022-07-06 11:38:18.663529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dfedcf64719'
down_revision = '3f2a3265ed46'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('category', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'category')
    # ### end Alembic commands ###
