"""empty message

Revision ID: 376cc3605b2d
Revises: b6326e7d085b
Create Date: 2022-06-20 10:25:20.690653

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '376cc3605b2d'
down_revision = 'b6326e7d085b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.Integer(), nullable=True))
    op.drop_constraint('user_user_type_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'user_type', ['user_type'], ['id'])
    op.drop_column('user', 'user_type_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key('user_user_type_id_fkey', 'user', 'user_type', ['user_type_id'], ['id'])
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###
