"""empty message

Revision ID: 3a77c6219b19
Revises: a6a19314df6b
Create Date: 2022-06-23 11:37:39.533228

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a77c6219b19'
down_revision = 'a6a19314df6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('is_approved_decorator', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'is_approved_decorator')
    # ### end Alembic commands ###
