"""empty message

Revision ID: 3cb71d8609dd
Revises: 31042c99f7d9
Create Date: 2022-06-16 18:59:31.175024

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3cb71d8609dd'
down_revision = '31042c99f7d9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'user_type', ['user_type_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'user_type_id')
    # ### end Alembic commands ###
