"""empty message

Revision ID: 3f2a3265ed46
Revises: 6f9eaa087d63
Create Date: 2022-07-06 11:37:51.658510

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f2a3265ed46'
down_revision = '6f9eaa087d63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'category')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
