"""empty message

Revision ID: 4c3c257c9233
Revises: 6ddb10dd5e9d
Create Date: 2022-07-06 14:08:00.586459

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4c3c257c9233'
down_revision = '6ddb10dd5e9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'start_time')
    op.drop_column('event', 'end_time')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('end_time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('event', sa.Column('start_time', postgresql.TIME(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
