"""empty message

Revision ID: 509c8e88ce2b
Revises: fafcf3065a89
Create Date: 2022-06-30 16:30:21.893029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '509c8e88ce2b'
down_revision = 'fafcf3065a89'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'decorator_type', ['decoration_type'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'decorator_type', type_='unique')
    # ### end Alembic commands ###
