"""empty message

Revision ID: 53fcb5737f25
Revises: 40be6bfedc23
Create Date: 2022-07-07 18:33:18.001700

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '53fcb5737f25'
down_revision = '40be6bfedc23'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('charges', sa.Integer(), nullable=False))
    op.add_column('event', sa.Column('decorator_charge', sa.Integer(), nullable=False))
    op.add_column('event', sa.Column('caterer_charge', sa.Integer(), nullable=False))
    op.add_column('event', sa.Column('venue_charge', sa.Integer(), nullable=False))
    op.add_column('event', sa.Column('Total_charge', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'Total_charge')
    op.drop_column('event', 'venue_charge')
    op.drop_column('event', 'caterer_charge')
    op.drop_column('event', 'decorator_charge')
    op.drop_column('event', 'charges')
    # ### end Alembic commands ###
