"""empty message

Revision ID: 548a569a43f5
Revises: 28b22f036034
Create Date: 2022-07-08 15:45:45.829553

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '548a569a43f5'
down_revision = '28b22f036034'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('event', sa.Column('Total_charge', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.drop_column('event', 'Total_charge')
    # ### end Alembic commands ###
