"""empty message

Revision ID: 56293fbbe386
Revises: 509c8e88ce2b
Create Date: 2022-07-01 10:25:18.326248

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56293fbbe386'
down_revision = '509c8e88ce2b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('decorator_type_decoration_type_key', 'decorator_type', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('decorator_type_decoration_type_key', 'decorator_type', ['decoration_type'])
    # ### end Alembic commands ###
