"""Event Category table created

Revision ID: 5c73978f5cc5
Revises: 6d0fa288e3de
Create Date: 2022-07-15 10:47:11.089821

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c73978f5cc5'
down_revision = '6d0fa288e3de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('event_category')
    # ### end Alembic commands ###
