"""empty message

Revision ID: 657213b81e68
Revises: 747f180ed3d6
Create Date: 2022-06-13 13:21:51.004785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '657213b81e68'
down_revision = '747f180ed3d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.TEXT(), nullable=True),
    sa.Column('contact_number', sa.String(), nullable=True),
    sa.Column('email_address', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venues')
    # ### end Alembic commands ###
