"""All Tables created

Revision ID: 695141086518
Revises: 37d4f43b46fd
Create Date: 2022-07-15 11:09:30.982658

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '695141086518'
down_revision = '37d4f43b46fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decorator_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decoration_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caterer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decorator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('venue_type', sa.Integer(), nullable=True),
    sa.Column('capacity', sa.Integer(), nullable=True),
    sa.Column('charges', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caterer_get_food_category',
    sa.Column('food_category_id', sa.Integer(), nullable=False),
    sa.Column('caterer_id', sa.Integer(), nullable=False),
    sa.Column('charges', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caterer_id'], ['caterer.id'], ),
    sa.ForeignKeyConstraint(['food_category_id'], ['food_category.id'], ),
    sa.PrimaryKeyConstraint('food_category_id', 'caterer_id')
    )
    op.create_table('decorator_get_types',
    sa.Column('decorator_id', sa.Integer(), nullable=False),
    sa.Column('decoration_type_id', sa.Integer(), nullable=False),
    sa.Column('charges', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['decoration_type_id'], ['decorator_type.id'], ),
    sa.ForeignKeyConstraint(['decorator_id'], ['decorator.id'], ),
    sa.PrimaryKeyConstraint('decorator_id', 'decoration_type_id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('category', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('decorator_id', sa.Integer(), nullable=True),
    sa.Column('caterer_id', sa.Integer(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('no_of_guests', sa.Integer(), nullable=False),
    sa.Column('is_approved_by_venue', sa.Boolean(), nullable=True),
    sa.Column('decorator_charge', sa.Integer(), nullable=True),
    sa.Column('caterer_charge', sa.Integer(), nullable=False),
    sa.Column('venue_charge', sa.Integer(), nullable=False),
    sa.Column('Total_charge', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caterer_id'], ['caterer.id'], ),
    sa.ForeignKeyConstraint(['decorator_id'], ['decorator.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue_get_caterer',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('caterer_id', sa.Integer(), nullable=False),
    sa.Column('is_approved_caterer', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['caterer_id'], ['caterer.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'caterer_id')
    )
    op.create_table('venue_get_decorator',
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.Column('decorator_id', sa.Integer(), nullable=False),
    sa.Column('is_approved_decorator', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['decorator_id'], ['decorator.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('venue_id', 'decorator_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('venue_get_decorator')
    op.drop_table('venue_get_caterer')
    op.drop_table('event')
    op.drop_table('decorator_get_types')
    op.drop_table('caterer_get_food_category')
    op.drop_table('venues')
    op.drop_table('decorator')
    op.drop_table('caterer')
    op.drop_table('food_category')
    op.drop_table('event_category')
    op.drop_table('decorator_type')
    # ### end Alembic commands ###
