"""empty message

Revision ID: 6ddb10dd5e9d
Revises: 8dfa30110e32
Create Date: 2022-07-06 14:06:57.808698

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6ddb10dd5e9d'
down_revision = '8dfa30110e32'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('start_time', sa.Time(), nullable=False))
    op.add_column('event', sa.Column('end_time', sa.Time(), nullable=False))
    op.drop_column('event', 'time')
    op.drop_column('event', 'duration')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('duration', postgresql.TIME(), autoincrement=False, nullable=False))
    op.add_column('event', sa.Column('time', postgresql.TIME(), autoincrement=False, nullable=False))
    op.drop_column('event', 'end_time')
    op.drop_column('event', 'start_time')
    # ### end Alembic commands ###
