"""empty message

Revision ID: 749ecca4e90a
Revises: 3cb71d8609dd
Create Date: 2022-06-17 14:08:17.174238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '749ecca4e90a'
down_revision = '3cb71d8609dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('decorator_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decoration_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('food_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('caterer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('food_category_id', sa.Integer(), nullable=True),
    sa.Column('charges', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['food_category_id'], ['food_category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decorator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('decoration_type_id', sa.Integer(), nullable=True),
    sa.Column('charges', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['decoration_type_id'], ['decorator_type.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('venues', sa.Column('user_id', sa.Integer(), nullable=True))
    op.add_column('venues', sa.Column('decorator_id', sa.Integer(), nullable=True))
    op.add_column('venues', sa.Column('caterer_id', sa.Integer(), nullable=True))
    op.add_column('venues', sa.Column('capacity', sa.Integer(), nullable=True))
    op.add_column('venues', sa.Column('charges', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'venues', 'user', ['user_id'], ['id'])
    op.create_foreign_key(None, 'venues', 'caterer', ['caterer_id'], ['id'])
    op.create_foreign_key(None, 'venues', 'decorator', ['decorator_id'], ['id'])
    op.drop_column('venues', 'email_address')
    op.drop_column('venues', 'contact_number')
    op.drop_column('venues', 'address')
    op.drop_column('venues', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('address', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('contact_number', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('email_address', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_constraint(None, 'venues', type_='foreignkey')
    op.drop_column('venues', 'charges')
    op.drop_column('venues', 'capacity')
    op.drop_column('venues', 'caterer_id')
    op.drop_column('venues', 'decorator_id')
    op.drop_column('venues', 'user_id')
    op.drop_table('decorator')
    op.drop_table('caterer')
    op.drop_table('food_category')
    op.drop_table('decorator_type')
    # ### end Alembic commands ###
