"""empty message

Revision ID: 8dfa30110e32
Revises: cded733038a6
Create Date: 2022-07-06 12:19:13.488615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8dfa30110e32'
down_revision = 'cded733038a6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('date', sa.Date(), nullable=False))
    op.add_column('event', sa.Column('time', sa.Time(), nullable=False))
    op.add_column('event', sa.Column('duration', sa.Time(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'duration')
    op.drop_column('event', 'time')
    op.drop_column('event', 'date')
    # ### end Alembic commands ###
