"""empty message

Revision ID: a6a19314df6b
Revises: 376cc3605b2d
Create Date: 2022-06-22 18:48:44.323444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a6a19314df6b'
down_revision = '376cc3605b2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('caterer_get_food_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('food_category_id', sa.Integer(), nullable=True),
    sa.Column('caterer_id', sa.Integer(), nullable=True),
    sa.Column('charges', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caterer_id'], ['caterer.id'], ),
    sa.ForeignKeyConstraint(['food_category_id'], ['food_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('decorator_get_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('decorator_id', sa.Integer(), nullable=True),
    sa.Column('decoration_type_id', sa.Integer(), nullable=True),
    sa.Column('charges', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['decoration_type_id'], ['decorator_type.id'], ),
    sa.ForeignKeyConstraint(['decorator_id'], ['decorator.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=20), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('decorator_id', sa.Integer(), nullable=True),
    sa.Column('caterer_id', sa.Integer(), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=False),
    sa.Column('duration', sa.DateTime(), nullable=False),
    sa.Column('no_of_guests', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['caterer_id'], ['caterer.id'], ),
    sa.ForeignKeyConstraint(['decorator_id'], ['decorator.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue_get_caterer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('caterer_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['caterer_id'], ['caterer.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('venue_get_decorator',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=True),
    sa.Column('decorator_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['decorator_id'], ['decorator.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint('caterer_food_category_id_fkey', 'caterer', type_='foreignkey')
    op.drop_column('caterer', 'food_category_id')
    op.drop_column('caterer', 'charges')
    op.drop_constraint('decorator_decoration_type_id_fkey', 'decorator', type_='foreignkey')
    op.drop_column('decorator', 'charges')
    op.drop_column('decorator', 'decoration_type_id')
    op.drop_constraint('venues_caterer_id_fkey', 'venues', type_='foreignkey')
    op.drop_constraint('venues_decorator_id_fkey', 'venues', type_='foreignkey')
    op.drop_column('venues', 'decorator_id')
    op.drop_column('venues', 'caterer_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('caterer_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('venues', sa.Column('decorator_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('venues_decorator_id_fkey', 'venues', 'decorator', ['decorator_id'], ['id'])
    op.create_foreign_key('venues_caterer_id_fkey', 'venues', 'caterer', ['caterer_id'], ['id'])
    op.add_column('decorator', sa.Column('decoration_type_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('decorator', sa.Column('charges', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('decorator_decoration_type_id_fkey', 'decorator', 'decorator_type', ['decoration_type_id'], ['id'])
    op.add_column('caterer', sa.Column('charges', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('caterer', sa.Column('food_category_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('caterer_food_category_id_fkey', 'caterer', 'food_category', ['food_category_id'], ['id'])
    op.drop_table('venue_get_decorator')
    op.drop_table('venue_get_caterer')
    op.drop_table('event')
    op.drop_table('decorator_get_types')
    op.drop_table('caterer_get_food_category')
    # ### end Alembic commands ###
