"""empty message

Revision ID: a92b899cdcb4
Revises: 56293fbbe386
Create Date: 2022-07-04 12:27:55.118027

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a92b899cdcb4'
down_revision = '56293fbbe386'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('is_approved_by_venue', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('event', 'is_approved_by_venue')
    # ### end Alembic commands ###
