"""empty message

Revision ID: c69e3e96f503
Revises: a92b899cdcb4
Create Date: 2022-07-04 15:57:40.881296

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c69e3e96f503'
down_revision = 'a92b899cdcb4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'venue_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('venue_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
