"""empty message

Revision ID: fcbe0acdae77
Revises: 0ad0da67640a
Create Date: 2022-07-08 12:52:39.794596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcbe0acdae77'
down_revision = '0ad0da67640a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'decorator_charge',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('event', 'decorator_charge',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
