"""empty message

Revision ID: fcdb39ddf6cb
Revises: 3a77c6219b19
Create Date: 2022-06-23 13:18:18.326878

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fcdb39ddf6cb'
down_revision = '3a77c6219b19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue_get_decorator', sa.Column('is_approved_decorator', sa.Boolean(), nullable=True))
    op.drop_column('venues', 'is_approved_decorator')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venues', sa.Column('is_approved_decorator', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('venue_get_decorator', 'is_approved_decorator')
    # ### end Alembic commands ###
